services:
  db:
    image: postgres:16.10
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.dev
    restart: on-failure

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379" 
    restart: always
  web:
    build: .
    command: uv run manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/auth/health/"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - .:/app

  celery-worker:
    build: .
    command: celery -A core worker -l info
    depends_on:
      - db
      - redis
      - web
    env_file:
      - .env.dev
    restart: on-failure
    volumes:
      - .:/app

volumes:
  pgdata:
