services:
  db:
    image: postgres:16.10
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  web:
    build: .
    command: uv run manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: always

volumes:
  pgdata:
