services:
  db:
    image: postgres:16.10
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  web:
    build: .
    command: uv run manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/auth/health/"]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  pgdata:
