services:
  db:
    image: postgres:16.10
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.prod
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/auth/health/"]
      interval: 10s
      timeout: 10s
      retries: 3

  celery-worker:
    build: .
    command: celery -A core worker -l info 
    depends_on:
      - db
      - redis
    env_file:
      - .env.prod
    restart: always
    volumes:
      - .:/app

volumes:
  pgdata: